version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /setup
  script: setup.app
  login: required
  secure: always

- url: /.*
  script: main.app
  login: required
  secure: always
